/*
 *    Webical - http://www.webical.org
 *    Copyright (C) 2007 Func. Internet Integration
 *
 *    This file is part of Webical.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package org.webical.web.component.calendar;

import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

import org.apache.wicket.markup.html.basic.Label;
import org.apache.wicket.markup.html.link.Link;
import org.webical.util.CalendarUtils;
import org.webical.web.action.AddEventAction;
import org.webical.web.action.IAction;
import org.webical.web.component.calendar.model.EventsModel;

/**
 * Panel displays the events of the user selected calendars for a particular day
 *
 * @author Mattijs Hoitink
 */

public abstract class DayViewPanel extends CalendarViewPanel {
	private static final long serialVersionUID = 1L;

	// Markup ID's
	private static final String ADD_EVENT_LINK_MARKUP_ID 	= "dayViewAddEventLink";
	private static final String DAY_HEADING_LABEL_MARKUP_ID = "dayHeadingLabel";
	private static final String EVENT_ITEM_MARKUP_ID = "eventItem";

	/** Contains the actions this panel can handle */
	@SuppressWarnings("unchecked")
	protected  static Class[] PANELACTIONS = new Class[] { };

	/**
	 * The identifier for the period this panel covers
	 */
	private final int viewPeriodId = Calendar.DAY_OF_MONTH;

	/**
	 * Length for the period this panel covers
	 */
	private final int viewPeriodLength = 1;

	/**
	 * Format of the period this panel covers
	 */
	private final String viewPeriodFormat = "MMMM dd, yyyy";

	/** The current date */
	private GregorianCalendar dayDate;

	private Label dayHeadingLabel;
	private Link addLink;
	private EventsListView eventsListView;

	/** The EventsModel for this panel */
	private EventsModel eventsModel;

	// The date range
	private Date startDate;
	private Date endDate;
	private SimpleDateFormat dateFormat;

	/**
	 * Constructor
	 * @param markupId The ID used in markup
	 * @param dayDate The date this panel is representing
	 */
	public DayViewPanel(String markupId, Calendar dayDate) {
		super(markupId, DayViewPanel.class);

		this.dayDate = (GregorianCalendar) dayDate;

		// Set the start time for the range
		startDate = CalendarUtils.getStartOfDay(this.dayDate.getTime());
		endDate = CalendarUtils.getEndOfDay(this.dayDate.getTime());

		eventsModel = new EventsModel(startDate, endDate);
		dateFormat = new SimpleDateFormat("EEEE", getLocale());

	}

	/* (non-Javadoc)
	 * @see org.webical.web.component.IAccessibilitySwitchingComponent#setupCommonComponents()
	 */
	public void setupCommonComponents() {
		dayHeadingLabel = new Label(DAY_HEADING_LABEL_MARKUP_ID, dateFormat.format(dayDate.getTime()));
		addOrReplace(dayHeadingLabel);
	}

	/* (non-Javadoc)
	 * @see org.webical.web.component.IAccessibilitySwitchingComponent#setupAccessibleComponents()
	 */
	public void setupAccessibleComponents() {

		eventsListView = new EventsListView(EVENT_ITEM_MARKUP_ID, eventsModel, dayDate) {
			private static final long serialVersionUID = 1L;

			@Override
			public void onAction(IAction action) {
				// Check if the action is in the ACTIONS array for this panel
				if(Arrays.asList(DayViewPanel.PANELACTIONS).contains(action.getClass())) {
					// Handle panel actions here
				} else {
					// Pass the action to the parent component
					DayViewPanel.this.onAction(action);
				}
			}

		};
		addOrReplace(eventsListView);

		//Add link to add an event
		addLink = new Link(ADD_EVENT_LINK_MARKUP_ID) {
			private static final long serialVersionUID = 1L;

			/**
			 * Change the content to the AddEditEventPanel
			 * @see wicket.markup.html.link.Link#onClick()
			 */
			@Override
			public void onClick() {
				// generate AddEventAction
				DayViewPanel.this.onAction(new AddEventAction(dayDate));
			}

		};
		add(addLink);

	}

	/* (non-Javadoc)
	 * @see org.webical.web.component.IAccessibilitySwitchingComponent#setupNonAccessibleComponents()
	 */
	public void setupNonAccessibleComponents() {
		// NOTHING TO DO
	}

	/**
	 * Handles actions generated by this panel.
	 * @param action The action to handle
	 */
	public abstract void onAction(IAction action);

	/* (non-Javadoc)
	 * @see org.webical.web.component.calendar.CalendarViewPanel#getViewPeriodFormat()
	 */
	@Override
	public String getViewPeriodFormat() {
		return this.viewPeriodFormat;
	}

	/* (non-Javadoc)
	 * @see org.webical.web.component.calendar.CalendarViewPanel#getViewPeriodId()
	 */
	@Override
	public int getViewPeriodId() {
		return this.viewPeriodId;
	}

	/* (non-Javadoc)
	 * @see org.webical.web.component.calendar.CalendarViewPanel#getViewPeriodLength()
	 */
	@Override
	public int getViewPeriodLength() {
		return this.viewPeriodLength;
	}

}
